//This c++ code is generated by PictoBlox

//Included Libraries
#include <Dabble.h>
#include <Servo.h>
#include <motor.h>

//MACROS are defined here
Motor Motor1(7, 8, 9);
Motor Motor2(5, 4, 6);

void setup() {
	//put your setup code here, to run once:
	Dabble.begin(9600);
	pinMode(10, OUTPUT);
	pinMode(11, OUTPUT);
	pinMode(12, OUTPUT);
	
	
}

void loop() {
	//put your main code here, to run repeatedly:
	Dabble.processInput();
	
	
	if(GamePad.isPressed(0)) {
		digitalWrite(10, true);
		digitalWrite(11, false);
		digitalWrite(12, false);
		Motor1.moveMotor(2.55*50);
		Motor2.moveMotor(2.55*50);
		delay(0.8 * 1000);
		Motor1.moveMotor(2.55*0);
		Motor2.moveMotor(2.55*0);
	}
	if(GamePad.isPressed(1)) {
		digitalWrite(10, false);
		digitalWrite(11, true);
		digitalWrite(12, false);
		Motor1.moveMotor(-2.55*65);
		Motor2.moveMotor(-2.55*65);
		delay(0.8 * 1000);
		Motor1.moveMotor(-2.55*0);
		Motor2.moveMotor(-2.55*0);
	}
	if(GamePad.isPressed(3)) {
		digitalWrite(10, false);
		digitalWrite(11, false);
		digitalWrite(12, true);
		Motor1.moveMotor(2.55*0);
		Motor2.moveMotor(2.55*45);
		delay(0.25 * 1000);
		Motor1.moveMotor(2.55*0);
		Motor2.moveMotor(-2.55*0);
	}
	if(GamePad.isPressed(2)) {
		analogWrite(11, 142);
		analogWrite(10, 101);
		digitalWrite(12, false);
		Motor1.moveMotor(2.55*45);
		Motor2.moveMotor(2.55*0);
		delay(0.25 * 1000);
		Motor1.moveMotor(-2.55*0);
		Motor2.moveMotor(2.55*0);
	}
}
